### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Exited with code 3  with latest pull of unfetter-ui

### ISSUE THREAD

**Issue by dRy3vd** [unfetter-discover/unfetter#1160] opened 2018-06-14 17:40 UTC
After the latest pull, I get this error when trying to bring up unfetter:

unfetter-ui                    | (node:26) UnhandledPromiseRejectionWarning: Error: Exited with code 3
unfetter-ui                    |     at ChildProcess.cp.once.code (/usr/share/unfetter-ui/node_modules/opn/index.js:82:13)
unfetter-ui                    |     at Object.onceWrapper (events.js:273:13)
unfetter-ui                    |     at ChildProcess.emit (events.js:182:13)
unfetter-ui                    |     at maybeClose (internal/child_process.js:957:16)
unfetter-ui                    |     at Socket.stream.socket.on (internal/child_process.js:378:11)
unfetter-ui                    |     at Socket.emit (events.js:182:13)
unfetter-ui                    |     at Pipe._handle.close [as _onclose] (net.js:598:12)
unfetter-ui                    | (node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
unfetter-ui                    | (node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dRy3vd** [comment] 2018-06-14 20:52
docker-compose -f docker-compose.development.yml up

Tried on both a RHELs box and my mac--same issue.

**Comment by dRy3vd** [comment] 2018-06-15 22:07
Same result with the command: 
`docker-compose -f docker-compose.yml -f docker-compose.development.yml up`

I was, however, semi-successful* with:
`docker-compose -f docker-compose.yml -f docker-compose.deploy.yml up`

So a few things:
1) Not sure why I am getting this error with the development compose
2) We should update the README.md in unfetter-discover/unfetter to reference the wiki for run cmd/modes.  It still lists the previous method: `docker-compose -f docker-compose.development.yml up`
3) Can you explain (or point me to) the reasoning for switching to two separate compose files to bring up unfetter?

*I'll log a separate issue/request around this.

**Comment by infosec-alchemist** [comment] 2018-06-18 15:36
The reason for the separate compose files is because we wanted the core compose file to have the majority of the configurations, while the dev, build, prod only have the delta.

In our next version, we will move to ansible rather than the compose files.  This might be easier if you know ansible, since we can make more complex configuration changes depending on the deployment type.

Or more confusing if someone doesn't know ansible.  But it will make it better for production deployments.

**Comment by j987987** [comment] 2018-06-19 17:06
Are you on the master or develop branch?  Our default branch on `unfetter` is Master, however, its develop on the other projects.  I would recommend checking out master on all projects.

The process which would be causing that issue is the `ng serve` command from the angular CLI.  Unfortunately, I am unable to reproduce this bug.

**Comment by infosec-alchemist** [comment] 2018-06-22 13:35
@dRy3vd, since @j987987  couldn't reproduce it and the error seen by @webiator seems to be intermittent and likely taken care of in the next version, I am going to close this issue.  If you are able to tell us how to recreate the problem using our current branches, please reopen.

Thanks

**Closed by infosec-alchemist** 2018-06-22 13:35 UTC
Labels: CUSTOMER REQUEST, bug, irreproducible
