### ISSUE TITLE
Using assessment selector, clicking edit, does not go to the proper assessment

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#822] opened 2018-03-12 21:41 UTC
If I'm in one assessment, I select the assessment selector, then click "edit" for another assessment, and I'm returned to the original assessment.

**Comment by webiator** [comment] 2018-03-13 11:20
I, for one, am unable to duplicate this behavior. The edit page can be slow to load, depending on the amount of activity you've engaged in with the application (seemingly due to slow garbage collection).

**Comment by mushinlogit** [comment] 2018-03-14 20:35
possibly fixed by unfetter-discover/unfetter#827

**Comment by mushinlogit** [comment] 2018-03-15 15:14
I tested again was not able to reproduce

**Closed** 2018-03-15 17:09 UTC
Labels: bug
